# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'GetGoTestApp' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  pod 'ReachabilitySwift'

  # Pods for GetGoTestApp

  target 'GetGoTestAppTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'GetGoTestAppUITests' do
    # Pods for testing
  end

end
